CREATE DATABASE IF NOT EXISTS LoginExcel;
USE LoginExcel;
CREATE TABLE IF NOT EXISTS usuarios(
	usuario VARCHAR(15) NOT NULL,
    contraseña VARCHAR(15) NOT NULL,
    PRIMARY KEY(usuario)
)ENGINE= INNODB DEFAULT CHARSET = LATIN1;